before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
      - mipsle
    goos:
      - darwin
      - linux
      - windows
    gomips:
      - softfloat
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - examples/config.yml
    - static/**/*
    - templates/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: dschanoeh
    name: what-to-wear
