language: go
env:
  secure: "NVoiEotj865FlHsBJxZTC1LfVPCTcCVMoymLD+D7Q71wByt7hOsc4x2BiM2112MxZ1YXNefQLTNmrCkmi8/nwAktfojT2bd44mEOOiKmuMtha7hNjJR03VRseZBV4hVFUru6TaCN64w0LUH5CI8HxcPDIXEVLHMKfvqEZ36fcF+mszmBEJ+TcSBTQpJqsfn1gSLrzTe95idxZE2cM7Wdk1ECT3qp7Bw5j1UvwyyLcl4fYZWt40kwJD7Y0k6B5VE2uHszAVXX7/S6F3qb02HINbYKAX+idoq8yXum2sLAaN3Tw8Q4DvQIJHLMsoizjpdlVuSBtLXtx7kFGWK30uCI9qxSUz1JvRT+UxQ+eZG6CaRj7fqdhXCRDYIF2FpnowFoUnxEYt5+Vhpb/sJ+9HTV4G36hmRIENnk9baf51zegqGe8sWLuR6dbIOjzPnHVZmSsfb6RjHx/J2tD72hN+AZavrdQbUZmhQ07hMji+vrtQHY3J1Or4tHZuZ6y/MEfQAjeGmjFXdE+iNRDFhUzlx8BmFhtuKPXmT2JHDc7tn5fOhttEzVg+kb2Bw5UtVVdhQmWnAm00n6w+O991xqWwNEH/eqeGxca5W90djknmaeGbS50dZN7wI9hHCSQkNXEO6G5QN8dH4HlMCDSfY2hVnqjvmEvGoX+55JOaLqC9Mc7QA="
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
