dist: focal
language: go
go:
- '1.15'
env:
  secure: "hN0hNwI8v7yhy8mNQMgbRZKA/pfhzMKbkAeu+dFqUYFiWnJh6+jgOmQoLk/3a9Gihckm8bUy6AdXM9f3fRBVGVHgXvF/thkqZ2FbkOYW2KuuDhYJIbjdP2ol2WzvLbFMkmmU0bJ0e/omD6k4HUV4hw8jS/+3eXQRcumTkzxphRvyKTKd23T3tOsJX6g6VwRlazqz6m3T1edNhmiBMteAMxxreOnsavB9x8onz/xr1IOjdd35hlafZj7FUTd+Eic445/utnxuoHm/otQiq3W7o1HJybd6u8ONLWxi4yAoo7sNYzoMkz4kpfWJcHPjjcPQtMX75DdAReDcekMl+466zEgbB1NZQRLv3cfwj32SA+d460VqsA7dlLy/ALZCWvbTfVszpDq6efJooJuooRHuw03Y+HxXuzr7546UtqsTSPv4H0JDRvVj7YxS9Kh8e27P9DqnrHoy7qN1zxOfGAPamNImMcrwo9+p1fSnBmH7h0ZrZyKDaDGvwsb32T8XpindWr1RFuPjAmppv5HNv2xlkBCB1zPvwy6k5wcLML02XHOVzZTnMeEA49c6Gxy42paSIavC4YOvg+yxx/j8e//MkRaW7zCUPwAdNwCw33XlAZYuDy1nLHz9Vw6CdF9rr7dsv7e29w7pCU9K5RwnSxF1bWkMWWPhHmUPLsCDqixnEnc="
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
