server:
  listen: ":7000"
cron_expression: "* * * * *"
open_weather_map:
  api_key: "[your key here]"
  latitude: 52.422994
  longitude: 10.791961
  language: "en"
imaging:
  width: 800
  height: 480
  chrome_binary: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  scrape_url: "http://127.0.0.1:7000"
  working_dir: "./static/"
  dithering: true
mqtt:
  broker_url: "127.0.0.1:1883"
  base_topic: "what-to-wear"
  chunk_size: 6000
messages:
  - message: >
      "Better bring an <i class='fas fa-umbrella'></i>."
    condition: "weather.CumulativePrecipitationTill(todayAt(20)) > 0.5"
  - message: "'It would be best to wear a ' + top + ' and ' + bottom + '.'"
    condition: "currentTime.Hour() < 20"
    variables:
      - name: "top"
        choices:
          - expression: "weather.AverageFeelsLikeTill(todayAt(20)) > 20"
            value: "t-shirt"
          - expression: "weather.AverageFeelsLikeTill(todayAt(20)) <= 20"
            value: "sweatshirt"
          - expression: "weather.AverageFeelsLikeTill(todayAt(20)) <= 12"
            value: "jacket"
          - expression: "weather.AverageFeelsLikeTill(todayAt(20)) <= 0"
            value: "winter coat"
      - name: "bottom"
        choices:
          - expression: "weather.AverageFeelsLikeTill(todayAt(20)) > 22"
            value: "shorts"
          - expression: "weather.AverageFeelsLikeTill(todayAt(20)) <= 22"
            value: "long pants"
  - message: >
      "It's <i class='fas fa-bicycle'></i> weather!"
    condition: "(weather.Current.Rain.OneHour + weather.Current.Snow.OneHour) < 0.2 && weather.Current.FeelsLike > 0"
  - message: >
      "It's <i class='fas fa-bicycle'></i> to work weather!"
    negative_message: >
      "No <i class='fas fa-bicycle'></i> to work weather <i class='fas fa-frown'></i>"
    condition: "weather.CumulativePrecipitationTill(todayAt(17)) < 0.2 && weather.DailyWeather[0].Temperature.Min > 0"
