server:
  listen: ":7000"
cron_expression: "* * * * *"
open_weather_map:
  api_key: "[your key here]"
  city: "Wolfsburg"
  language: "en"
imaging:
  width: 800
  height: 480
  chrome_binary: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  scrape_url: "http://127.0.0.1:7000"
  working_dir: "./static/"
  dithering: true
mqtt:
  broker_url: "127.0.0.1:1883"
  base_topic: "what-to-wear"
  chunk_size: 6000
messages:
  - message: >
      "Better bring an <i class='fas fa-umbrella'></i>."
    condition: "forecast.CumulativePrecipitationTill(20) > 0.5"
  - message: "'It would be best to wear a ' + top + ' and ' + bottom + '.'"
    variables:
      - name: "top"
        choices:
          - expression: "forecast.AverageFeelsLikeTill(20) > 20"
            value: "t-shirt"
          - expression: "forecast.AverageFeelsLikeTill(20) <= 20"
            value: "sweatshirt"
          - expression: "forecast.AverageFeelsLikeTill(20) <= 12"
            value: "jacket"
          - expression: "forecast.AverageFeelsLikeTill(20) <= 0"
            value: "winter coat"
      - name: "bottom"
        choices:
          - expression: "forecast.AverageFeelsLikeTill(20) > 20"
            value: "shorts"
          - expression: "forecast.AverageFeelsLikeTill(20) <= 20"
            value: "long pants"
  - message: >
      "It's <i class='fas fa-bicycle'></i> weather!"
    condition: "(rain3h + snow3h) < 0.2 && feelsLike > 0"
  - message: >
      "It's <i class='fas fa-bicycle'></i> to work weather!"
    negative_message: >
      "No <i class='fas fa-bicycle'></i> to work weather <i class='fas fa-frown'></i>"
    condition: "forecast.CumulativePrecipitationTill(17) < 0.2 && tempMin > 0"
